"""add research_notes to campaigns

Revision ID: 130bff812dd0
Revises: 6ad630632647
Create Date: 2026-07-24 16:49:18.811154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130bff812dd0'
down_revision: Union[str, Sequence[str], None] = '6ad630632647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('research_notes', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'research_notes')
    # ### end Alembic commands ###
