"""add indexes for campaign headline and budget_spent sorting

Revision ID: 46ca5e2e642f
Revises: fe6ff3f87aaf
Create Date: 2026-08-18 19:54:29.507285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ca5e2e642f'
down_revision: Union[str, Sequence[str], None] = 'fe6ff3f87aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_campaigns_budget_spent'), 'campaigns', ['budget_spent'], unique=False)
    op.create_index(op.f('ix_campaigns_headline'), 'campaigns', ['headline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_headline'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_budget_spent'), table_name='campaigns')
    # ### end Alembic commands ###
