"""add user_id created_at index on events

Revision ID: 6ad630632647
Revises: 84ef8f8f7ff4
Create Date: 2026-07-23 21:39:52.403225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad630632647'
down_revision: Union[str, Sequence[str], None] = '84ef8f8f7ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_events_user_id_created_at', 'events', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_user_id_created_at', table_name='events')
    # ### end Alembic commands ###
