"""add users table, reactions.user_id fk

Revision ID: 97ebb958daf2
Revises: b3ac0b70eaf7
Create Date: 2026-08-16 17:01:08.450829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ebb958daf2'
down_revision: Union[str, Sequence[str], None] = 'b3ac0b70eaf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub')
    )

    # reactions.user_id currently holds pre-auth session UUIDs (from the
    # anonymous-guest system, see docs/auth_plan.md) that don't correspond
    # to any real account and can't be cast to the new integer FK -- wipe
    # them before the type change, matching the explicit "wipe and use the
    # new design" call made when accounts were first proposed for this
    # table (see the Reaction model's original design conversation).
    op.execute("DELETE FROM reactions")

    op.alter_column('reactions', 'user_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='user_id::integer')
    op.create_foreign_key(None, 'reactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.alter_column('reactions', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_table('users')
    # ### end Alembic commands ###
