"""create reactions table

Revision ID: b3ac0b70eaf7
Revises: bf2edd83f9b3
Create Date: 2026-08-09 13:16:35.637028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ac0b70eaf7'
down_revision: Union[str, Sequence[str], None] = 'bf2edd83f9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'campaign_id', name='uq_reactions_user_campaign')
    )
    # ### end Alembic commands ###

    # One-time backfill: reactions didn't exist as a concept before this
    # migration, so seed current-state from each user/campaign's most recent
    # reaction-type Event, rather than silently starting everyone at "no
    # reaction" and losing real history.
    op.execute(
        """
        INSERT INTO reactions (user_id, campaign_id, reaction, created_at, updated_at)
        SELECT DISTINCT ON (user_id, campaign_id) user_id, campaign_id, event_type, created_at, created_at
        FROM events
        WHERE event_type IN ('like', 'dislike', 'interested')
        ORDER BY user_id, campaign_id, created_at DESC
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactions')
    # ### end Alembic commands ###
