"""add onboarding_completed to users

Revision ID: c835b6e52c74
Revises: 97ebb958daf2
Create Date: 2026-08-17 13:34:35.114538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c835b6e52c74'
down_revision: Union[str, Sequence[str], None] = '97ebb958daf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    # ### end Alembic commands ###
