"""add indexes for campaign filtering and sorting

Revision ID: fe6ff3f87aaf
Revises: bed5a742999d
Create Date: 2026-08-18 19:47:45.939059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6ff3f87aaf'
down_revision: Union[str, Sequence[str], None] = 'bed5a742999d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_campaigns_budget_total'), 'campaigns', ['budget_total'], unique=False)
    op.create_index(op.f('ix_campaigns_category'), 'campaigns', ['category'], unique=False)
    op.create_index(op.f('ix_campaigns_created_at'), 'campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_created_at'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_category'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_budget_total'), table_name='campaigns')
    # ### end Alembic commands ###
